### PR TITLE
Update dependencies to fix vulnerabilities

### PR DESCRIPTION
**Pull request by striezel**
Updates various dependencies to fix vulnerabilities in them. See the individual commit messages for the fixed vulnerabilities.

### Luxtorpeda Client Submissions

* [x] Have you verified that the code changes in the pull request are related to only the items you wish to change?
* [x] Have you ensured that there is not already a pull request or active feature for the one you are adding?

### CODE REVIEW

**Comment by d10sfan** [comment]
@striezel Thanks for the PR! Was this made using a tool or done by hand? Curious because if it was a tool, I could add that as part of the github actions in the future.

**Comment by striezel** [comment]
> Was this made using a tool or done by hand?

For the detection of those issues I used [cargo audit](https://github.com/rustsec/rustsec/tree/main/cargo-audit), but I updated each of these manually one at a time with `cargo update --package=package-name-here` to avoid breaking the build. That's also why there are several commits, one for each major crate updated.

Basically, one can install `cargo audit` by typing

```
cargo install cargo-audit
```

and after that you can just run `cargo audit` in any working copy of a Rust project. It will print a list of packages with known vulnerabilities and possible solutions.

> Curious because if it was a tool, I could add that as part of the github actions in the future.

In theory, that can be done. Some Rust projects already have done it. However, this may cause your CI pipeline to fail and keep on failing for weeks or even months, because some crates take quite a long time to fix their stuff. So while it is good to get an idea of vulnerable crates, it can quickly become a source of disappointment when a project depends on crates whose owners don't care that much to fix their code or even abandoned those crates.

----
Futhermore, when you run `cargo audit` on this PR's code, you will see that still some vulnerabilities exist. One reason is that some of that stuff has not been fixed (e. g. the `zip` crate which even in the newest version still uses an unmaintained crate as dependency). Also just doing `cargo update` in the hope to fix everything possible will break the current CI as it does not build with rustc 1.56.

**Comment by striezel** [comment]
@d10sfan:
Just added two more updates, so that all the serious vulnerabilities are taken care of. `cargo audit` still shows two warnings, but that should not abort any CI pipeline, should you decide to use `cargo audit` there. So feel free to go ahead with that.

**Comment by d10sfan** [comment]
@striezel Thanks, this looks good, I'll have it in the next release when it's official.

**Comment by d10sfan** [comment]
@striezel Thanks for the heads up about cargo audit as well, I added it for the PR checks for the future.

**Pull request merged**
