### PR TITLE
Show icon in taskbar

### PR DESCRIPTION
**Pull request by d10sfan**
### Luxtorpeda Client Submissions

* [ ] Have you verified that the code changes in the pull request are related to only the items you wish to change?
* [ ] Have you run the build locally and ensured the changes allowed you to launch and play the Steam game?
* [ ] Have you ensured that there is not already a pull request or active feature for the one you are adding?

### CODE REVIEW

**Comment by ThibaultLemaire** [comment]
Everything builds, runs, and behaves properly, except that the client is now blocking compositing.

In KDE, compositing is required for animations (e.g. smooth transitions between virtual desktops), and without them the desktop grid is disabled, which kind of defeats the purpose here.

In KDE's Sytem Settings > Compositor there is a checkbox "Allow applications to block compositing". When disabled, I can open the desktop grid and move the client window around as expected. (The icon always appears in the taskbar, whether compositing is enabled or not.)

From this checkbox's tooltip:

> Applications can set hint to block compositing when the window is open.
> This brings performance improvements for e.g. games.

So I'm guessing we're just missing an SDL setting somewhere.

Also, it makes sense for the client not to disable compositing for desktops other than KDE. It's a GUI, not a game. It does not have heavy graphics requirements at all.

**Comment by d10sfan** [comment]
@ThibaultLemaire That was one of the benefits of the sdl utility flag, in that it did not attempt to disable compositing.

I am setting  sdl2::hint::set("SDL_HINT_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR", "0"); which should be telling it not to do that, but it does not seem to be working.

I'll do some research, as well if you have any ideas feel free to let me know

**Comment by ThibaultLemaire** [comment]
I found [this relevant bit of code in SDL2](https://github.com/libsdl-org/SDL/blob/63b3b9a5582e7936af0f79bd602db1400e155d42/src/video/x11/SDL_x11window.c#L602) but I'm not sure what to make of it

**Comment by d10sfan** [comment]
@ThibaultLemaire That was one of the benefits of the sdl utility flag, in that it did not attempt to disable compositing.

I am setting  sdl2::hint::set("SDL_HINT_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR", "0"); which should be telling it not to do that, but it does not seem to be working.

I'll do some research, as well if you have any ideas feel free to let me know

> I found [this relevant bit of code in SDL2](https://github.com/libsdl-org/SDL/blob/63b3b9a5582e7936af0f79bd602db1400e155d42/src/video/x11/SDL_x11window.c#L602) but I'm not sure what to make of it

Yeah, from my understanding that's what is supposed to use that sdl2 hint I'm setting to signal not to disable the compositor. You can see the x11 side here: https://specifications.freedesktop.org/wm-spec/wm-spec-latest.html#idm46409506222736

**Comment by ThibaultLemaire** [comment]
I've tried

``` rust
sdl2::hint::set(
        "SDL_HINT_X11_WINDOW_TYPE",
        "_NET_WM_WINDOW_TYPE_NORMAL"
    );
```

to try to force window type without triggering compositor hint setting, but it does not seem to change anything at all. I'm beginning to think hints aren't read correctly.

**Comment by ThibaultLemaire** [comment]
Ok. Got it. It's just a typo:

https://github.com/libsdl-org/SDL/blob/3861c557da1494e91f33e328ba29ad5d25246e1c/include/SDL_hints.h#L1684

You should change your line to "SDL_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR" not "SDL_HINT_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR"

**Comment by ThibaultLemaire** [comment]
Or rather [sdl2_sys](https://rust-sdl2.github.io/rust-sdl2/sdl2_sys/index.html)::[SDL_HINT_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR](https://rust-sdl2.github.io/rust-sdl2/sdl2_sys/constant.SDL_HINT_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR.html) to avoid any mistakes in the future.

**Comment by d10sfan** [comment]
@ThibaultLemaire Thanks for the assist, I tried with the corrected hint value and it seems to be working now. Can you try the latest from this branch and see if it works for you as well?

**Comment by ThibaultLemaire** [comment]
It works

**Comment by d10sfan** [comment]
@ThibaultLemaire Ok great! I'm going to go ahead and merge this for a new release. Let me know if you think of any other improvements

**Pull request merged**
